### ISSUE TITLE
Dividing by h.opt twice

### ISSUE THREAD

**Issue by tedwestling** [ehkennedy/npcausal#2]
https://github.com/ehkennedy/npcausal/blob/bb86234cce9ec6117bf2258663cbf46b0cc83fcf/R/ctseff.R#L98

Hi Edward,

Here's the line that I was confused by in the csteff function. In particular, I wasn't sure why you divide by h.opt twice in `kern.std <- (kern(a.std)/h.opt)/h.opt`. Seemed to me like it should be  `kern.std <- (kern(a.std)/h.opt)`, but maybe I missed something.

Best,
Ted

**Comment by ehkennedy** [comment]
Thanks again for finding this Ted!
